export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          phone: string;
          email: string | null;
          role: 'farmer' | 'staff' | 'admin';
          status: 'active' | 'pending' | 'suspended';
          village: string | null;
          district: string | null;
          state: string | null;
          preferred_language: string | null;
          primary_crop: string | null;
          land_acres: number | null;
          kisan_card_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          phone: string;
          email?: string | null;
          role?: 'farmer' | 'staff' | 'admin';
          status?: 'active' | 'pending' | 'suspended';
          village?: string | null;
          district?: string | null;
          state?: string | null;
          preferred_language?: string | null;
          primary_crop?: string | null;
          land_acres?: number | null;
          kisan_card_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          phone?: string;
          email?: string | null;
          role?: 'farmer' | 'staff' | 'admin';
          status?: 'active' | 'pending' | 'suspended';
          village?: string | null;
          district?: string | null;
          state?: string | null;
          preferred_language?: string | null;
          primary_crop?: string | null;
          land_acres?: number | null;
          kisan_card_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      procurement_centers: {
        Row: {
          id: string;
          code: string;
          name: string;
          district: string;
          crowd_level: 'low' | 'moderate' | 'high';
          farmers_waiting: number;
          avg_wait_min: number;
          capacity_pct: number;
          is_best_choice: boolean;
          map_x: number;
          map_y: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          district: string;
          crowd_level?: 'low' | 'moderate' | 'high';
          farmers_waiting?: number;
          avg_wait_min?: number;
          capacity_pct?: number;
          is_best_choice?: boolean;
          map_x?: number;
          map_y?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          district?: string;
          crowd_level?: 'low' | 'moderate' | 'high';
          farmers_waiting?: number;
          avg_wait_min?: number;
          capacity_pct?: number;
          is_best_choice?: boolean;
          map_x?: number;
          map_y?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      tokens: {
        Row: {
          id: string;
          token_number: string;
          user_id: string;
          center_id: string;
          farmer_name: string;
          crop: string;
          quantity_quintals: number;
          appointment_date: string;
          appointment_time: string;
          queue_position: number;
          status: 'confirmed' | 'checked_in' | 'quality_checked' | 'completed' | 'cancelled';
          moisture_pct: number | null;
          express_pass: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          token_number: string;
          user_id: string;
          center_id: string;
          farmer_name: string;
          crop: string;
          quantity_quintals: number;
          appointment_date: string;
          appointment_time: string;
          queue_position?: number;
          status?: 'confirmed' | 'checked_in' | 'quality_checked' | 'completed' | 'cancelled';
          moisture_pct?: number | null;
          express_pass?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          token_number?: string;
          user_id?: string;
          center_id?: string;
          farmer_name?: string;
          crop?: string;
          quantity_quintals?: number;
          appointment_date?: string;
          appointment_time?: string;
          queue_position?: number;
          status?: 'confirmed' | 'checked_in' | 'quality_checked' | 'completed' | 'cancelled';
          moisture_pct?: number | null;
          express_pass?: boolean | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      procurement_records: {
        Row: {
          id: string;
          receipt_number: string;
          token_id: string | null;
          user_id: string;
          center_id: string;
          farmer_name: string;
          farmer_phone: string;
          crop: string;
          variety: string;
          quantity_quintals: number;
          moisture_pct: number;
          trash_pct: number;
          quality_grade: string;
          rate_per_quintal: number;
          gross_amount: number;
          moisture_deduction: number;
          handling_deduction: number;
          total_deductions: number;
          final_payable_amount: number;
          verified_by: string;
          status: 'Weighed' | 'Verified' | 'Approved' | 'Payment Initiated' | 'Payment Completed';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          receipt_number: string;
          token_id?: string | null;
          user_id: string;
          center_id: string;
          farmer_name: string;
          farmer_phone: string;
          crop: string;
          variety?: string;
          quantity_quintals: number;
          moisture_pct?: number;
          trash_pct?: number;
          quality_grade?: string;
          rate_per_quintal: number;
          gross_amount: number;
          moisture_deduction?: number;
          handling_deduction?: number;
          total_deductions?: number;
          final_payable_amount: number;
          verified_by: string;
          status?: 'Weighed' | 'Verified' | 'Approved' | 'Payment Initiated' | 'Payment Completed';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          receipt_number?: string;
          token_id?: string | null;
          user_id?: string;
          center_id?: string;
          farmer_name?: string;
          farmer_phone?: string;
          crop?: string;
          variety?: string;
          quantity_quintals?: number;
          moisture_pct?: number;
          trash_pct?: number;
          quality_grade?: string;
          rate_per_quintal?: number;
          gross_amount?: number;
          moisture_deduction?: number;
          handling_deduction?: number;
          total_deductions?: number;
          final_payable_amount?: number;
          verified_by?: string;
          status?: 'Weighed' | 'Verified' | 'Approved' | 'Payment Initiated' | 'Payment Completed';
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          payment_number: string;
          procurement_id: string | null;
          user_id: string;
          farmer_name: string;
          farmer_phone: string;
          crop: string;
          quantity_quintals: number;
          rate_per_quintal: number;
          gross_amount: number;
          deductions: number;
          final_payable_amount: number;
          payment_method: 'dbt' | 'upi' | 'neft';
          bank_last4: string;
          center_name: string;
          idempotency_key: string;
          provider_reference_id: string;
          status: 'pending' | 'processing' | 'successful' | 'failed' | 'on_hold';
          failure_reason: string | null;
          retry_count: number;
          approved_by: string | null;
          approved_at: string | null;
          completed_at: string | null;
          gateway_order_id: string | null;
          gateway_payment_id: string | null;
          gateway_signature: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          payment_number: string;
          procurement_id?: string | null;
          user_id: string;
          farmer_name: string;
          farmer_phone: string;
          crop: string;
          quantity_quintals: number;
          rate_per_quintal: number;
          gross_amount: number;
          deductions?: number;
          final_payable_amount: number;
          payment_method?: 'dbt' | 'upi' | 'neft';
          bank_last4?: string;
          center_name: string;
          idempotency_key: string;
          provider_reference_id: string;
          status?: 'pending' | 'processing' | 'successful' | 'failed' | 'on_hold';
          failure_reason?: string | null;
          retry_count?: number;
          approved_by?: string | null;
          approved_at?: string | null;
          completed_at?: string | null;
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          gateway_signature?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          payment_number?: string;
          procurement_id?: string | null;
          user_id?: string;
          farmer_name?: string;
          farmer_phone?: string;
          crop?: string;
          quantity_quintals?: number;
          rate_per_quintal?: number;
          gross_amount?: number;
          deductions?: number;
          final_payable_amount?: number;
          payment_method?: 'dbt' | 'upi' | 'neft';
          bank_last4?: string;
          center_name?: string;
          idempotency_key?: string;
          provider_reference_id?: string;
          status?: 'pending' | 'processing' | 'successful' | 'failed' | 'on_hold';
          failure_reason?: string | null;
          retry_count?: number;
          approved_by?: string | null;
          approved_at?: string | null;
          completed_at?: string | null;
          gateway_order_id?: string | null;
          gateway_payment_id?: string | null;
          gateway_signature?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      msp_prices: {
        Row: {
          id: string;
          crop_name: string;
          category: string;
          msp_rate_per_quintal: number;
          previous_year_msp: number;
          effective_season: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          crop_name: string;
          category: string;
          msp_rate_per_quintal: number;
          previous_year_msp: number;
          effective_season?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          crop_name?: string;
          category?: string;
          msp_rate_per_quintal?: number;
          previous_year_msp?: number;
          effective_season?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
